// File generated by FlutterFire CLI.
// This file should be generated using: flutterfire configure
// After installing FlutterFire CLI: dart pub global activate flutterfire_cli
// Then run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ifs5UeqnFgw_nue9xrYn-Omv4BQnYHI',
    appId: '1:813025404663:web:2338e302be269fbb4395f2',
    messagingSenderId: '813025404663',
    projectId: 'baitapth2',
    authDomain: 'baitapth2.firebaseapp.com',
    storageBucket: 'baitapth2.firebasestorage.app',
    measurementId: 'G-58M7GTE5B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaLvBNhmEC7LMUoZz1tNpOGTwGxqEUJ0',
    appId: '1:813025404663:android:bc1920e7503c500c4395f2',
    messagingSenderId: '813025404663',
    projectId: 'baitapth2',
    storageBucket: 'baitapth2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vMc15JlNrH9VFiB3cvKBFtzUKZUgMA4',
    appId: '1:813025404663:ios:9f2621426c3c4b7f4395f2',
    messagingSenderId: '813025404663',
    projectId: 'baitapth2',
    storageBucket: 'baitapth2.firebasestorage.app',
    iosBundleId: 'com.example.baitap3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vMc15JlNrH9VFiB3cvKBFtzUKZUgMA4',
    appId: '1:813025404663:ios:9f2621426c3c4b7f4395f2',
    messagingSenderId: '813025404663',
    projectId: 'baitapth2',
    storageBucket: 'baitapth2.firebasestorage.app',
    iosBundleId: 'com.example.baitap3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Ifs5UeqnFgw_nue9xrYn-Omv4BQnYHI',
    appId: '1:813025404663:web:ca2294eda4a42b4a4395f2',
    messagingSenderId: '813025404663',
    projectId: 'baitapth2',
    authDomain: 'baitapth2.firebaseapp.com',
    storageBucket: 'baitapth2.firebasestorage.app',
    measurementId: 'G-VT0DJLQ9HD',
  );

}