// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4WYHp2hxMcylKZSbtTQNRpIVAUmq8LHk',
    appId: '1:534099632201:web:60374fd171e74d120adf98',
    messagingSenderId: '534099632201',
    projectId: 'ltmobileth2',
    authDomain: 'ltmobileth2.firebaseapp.com',
    storageBucket: 'ltmobileth2.firebasestorage.app',
    measurementId: 'G-PVT3JDE9YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxHI88O_a-G14OBgOgHwvKhe2pOo4eBnI',
    appId: '1:534099632201:android:307b52568acde7a30adf98',
    messagingSenderId: '534099632201',
    projectId: 'ltmobileth2',
    storageBucket: 'ltmobileth2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfxkF0b6OfGbSh_Z68yblvjmde9Oo21GM',
    appId: '1:534099632201:ios:1f4beb0188366ff60adf98',
    messagingSenderId: '534099632201',
    projectId: 'ltmobileth2',
    storageBucket: 'ltmobileth2.firebasestorage.app',
    iosBundleId: 'com.example.baitap1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfxkF0b6OfGbSh_Z68yblvjmde9Oo21GM',
    appId: '1:534099632201:ios:1f4beb0188366ff60adf98',
    messagingSenderId: '534099632201',
    projectId: 'ltmobileth2',
    storageBucket: 'ltmobileth2.firebasestorage.app',
    iosBundleId: 'com.example.baitap1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4WYHp2hxMcylKZSbtTQNRpIVAUmq8LHk',
    appId: '1:534099632201:web:1fb42bba97d04d930adf98',
    messagingSenderId: '534099632201',
    projectId: 'ltmobileth2',
    authDomain: 'ltmobileth2.firebaseapp.com',
    storageBucket: 'ltmobileth2.firebasestorage.app',
    measurementId: 'G-G5DKV0YJVD',
  );
}
